### ISSUE TITLE
allow error logs

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#11]
Maybe find a way, in both windows and linux, to get an error log created so that failures can be tracked.

**Comment by reactor7171** [comment]
I am going to close both #15 and #11 in pro of ticket #78.

The objective of the ticket is improve overall logging on the vulnwhisperer project, including status of jobs and error logs in order to track failures on the project.

This will also be easier to track once python tests are implemented in order to make sure that every code addition is not breaking other code parts from the project.
