### ISSUE TITLE
[Nessus] Scans Imported from other Nessus not detected by VulnWhisperer

### ISSUE THREAD

**Issue by janniten** [HASecuritySolutions/VulnWhisperer#110]
Hi, I'm not able to fetch nessus imported scans. I mean, scans done in another nessus and imported to the one vuln whispered is connected
Is it possible?
Thank you
Regards
Ana

**Comment by reactor7171** [comment]
Hi @janniten,
Can you give us a bit more info about what is the issue you are encountering? Are those scans imported to the "My Scans" folder? If so, they should also download when not detected in the local folder.
If you had a specific error it would help out.

Cheers!

**Comment by janniten** [comment]
Hi Quim,
I get no error. It simply does not detect the imported scan.
The scan is imported in My Scans; I've tried importing it in .nessus format and in nessus_db format.
The scan is successfully imported but VulnWhisperer is not able to recognize it.
Attached a scrrenshot of the nessus scans. 
Regards and thank you!
Ana

![nessus](https://user-images.githubusercontent.com/33020901/47141267-9333cf00-d2c0-11e8-843d-d28ff435548b.JPG)

**Comment by reactor7171** [comment]
Hi @janniten,
So, just to make sure we are in the same page:
- You exported a scan from an external Nessus
- You imported that scan to **your** Nessus in several ways (CSV, .nessus and nessus_db), so all of that scan's data is now on your Nessus.
- When VulnWhisperer runs, the imported scan is not detected, thus it continues and exits when finishing the rest of the local scans.

Just to make sure that it is like this, could you confirm that inside of the folder "./data/nessus/My\Scans/" its does not exist the "TEST***.csv" file of this scan, in case it slipped and you didn't notice?

Cheers!
Quim

**Comment by janniten** [comment]
Hi Quim,
Yes, it is in the way you have described.
I checked the nessus folder (in my case /opt/vulnwhisperer/nessus/My\Scans/) and does not contains the TEST***.csv

Thank you!
Regards
Ana

**Comment by reactor7171** [comment]
Hi @janniten,

I believe the issue is at the following lines:
https://github.com/qmontal/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L318
https://github.com/qmontal/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L331
https://github.com/qmontal/VulnWhisperer/blob/master/vulnwhisp/vulnwhisp.py#L387
As it is checking for the status to be exactly "completed", and probably the status of your scan would be something like "imported"; as you can see on the pic that you posted, next to the "Last Modified" date of each scan, there is an icon reflecting the status of the scan, and the imported one has a different status than the completed one.

Currently we are working on important structural changes of VulnWhisperer, so any PR is very welcomed :)

**Comment by janniten** [comment]
Thank you Quim
Regards
Ana

**Comment by janniten** [comment]
Hi Quim,
I was able to fetch the data from the imported scan modifying the condition in the lines you told me.
Thank you!
Regards
Ana

**Comment by reactor7171** [comment]
Hi @janniten,
Could you share what was the status value for the imported scan, in case we are able to implement it in the future? Also, if you did your own improvement on the code to include both successful scans as well as imported, feel free to do PR so that we merge it in the current code for other users :)
BR,
Quim

**Comment by bmarsh9** [comment]
Is there a update on this? I have also imported scans and VulnWhisp won't read it.

**Comment by reactor7171** [comment]
Hey @bm1391,

There isn't still any update and with the current lack of resources, even though I would love to have it implemented right now, it is not a priority right now. Once we have the major structural changes done and unified all of the results of the modules as mentioned in #81, then we will start resolving bugs.

Until then, the only things I can ask unfortunately are either bearing with us or contributing with the change as a PR :)

Thanks for the understanding.

**Comment by reactor7171** [comment]
This should have been solved now with the last commit.
