### ISSUE TITLE
Bug special characters

### ISSUE THREAD

**Issue by psantos1** [HASecuritySolutions/VulnWhisperer#114]
Hi Austin,

Just to let you know or anyone else that bumps into the same issue that I was having. The problem was that I had a special character in my Nessus password that needed to be escaped, and until I figured that out I was getting this from the software:

[INFO] Connected to database at /opt/VulnWhisperer/data/database/report_tracker.db
[INFO] Attempting to connect to nessus...
[FAIL] Could not login to Nessus
[FAIL] Could not properly load your config!
Reason: [FAIL] Could not connect to nessus -- Please verify your settings in configs/frameworks.ini are correct and try again.
Reason: [FAIL] Could not login to Nessus

The easy solution is to escape it directly in the password.
By special characters, I mean chars like \ " and so on...

Thanks.

**Comment by reactor7171** [comment]
Hey @psantos1,
Thanks for telling us about this, will add this to the FAQ in case other users have the same issue; I remember there was a similar problem with the qualysapi dependency when doing the connection, so it will be good anyway to have it.

In order to solve it, the easiest would be the regex escaping mentioned at https://stackoverflow.com/questions/18935754/how-to-escape-special-characters-of-a-string-with-single-backslashes/18935765#18935765.

We will have this fixed when we can :)

Cheers!
