### ISSUE TITLE
Qualys and Qualys_Vuln sections

### ISSUE THREAD

**Issue by psantos1** [HASecuritySolutions/VulnWhisperer#115]
Hi,

I was trying to make VulnWhisperer work only with the qualys_vuln section, and for that reason, I only had set the values concerning that segment. When running the software, I noticed that the values at that section are useless, only the "enabled" flag is being taken under consideration because the qualyslib used for establishing the connection to Qualys is looking at the [qualys] section of the config file. So even though this section contains the "enabled" flag false, the values must be set in order to use the [qualys_vuln] section. 

Ex:

[qualys]
enabled=false
hostname = qualysapi.qualys.eu
username = XXXXXXXXX
password = XXXXXXXXX
write_path=/opt/VulnWhisperer/data/qualys/
db_path=/opt/VulnWhisperer/data/database
verbose=true
max_retries = 10
template_id = 126024

[qualys_vuln]
enabled=true
hostname = testurl
username = testuser
password = testpw
write_path=/opt/VulnWhisperer/data/qualys/
db_path=/opt/VulnWhisperer/data/database
verbose=true

Cheers.

**Comment by reactor7171** [comment]
Hi @psantos1,

This is something that has already been fixed in #107, but is still in the testing branch as I was waiting for having the qualysapi library updated on pip and be able to get rid completely of the qualysapi fork that we are currently maintaining in the repository.

If you want to have the patched version for that feature and help out testing, you can use the testing branch code :)

Cheers!

**Comment by reactor7171** [comment]
I need to recheck this after going back to the vulnwhisperer qualysapi fork, I am not sure it is working anymore and might need a fix.

**Comment by psantos1** [comment]
Hi @qmontal, if I stumble across this bug again I'll give you a heads up.
