### ISSUE TITLE
Question: Missing fields in cvs present in Nessus XML report

### ISSUE THREAD

**Issue by janniten** [HASecuritySolutions/VulnWhisperer#117]
Hi,
I've noticed that there are some fields present in the XML report, such as

- exploit_available
- patch_publication_date
- bid
etc

that are not  in the csv and therefore there are not indexing into Elastic.
Is it planned to extend the number of fields to cover all the ones we have in the XML export?
Thank you
Regards
Ana

**Comment by reactor7171** [comment]
Hi @janniten,

Yes, this is something related to #42. The main issue now is that the big structural changes are priority, but at some point it would be good to move to the XML format or even the nessus file one, and once that was done, then we could just enable parsing local files with the same implementation as requested in #64.

These are things that we have in our backlog, but unfortunately due to the lack of resources and the current priorities it doesn't seem to be able to have them accomplished in an early future.

BR,
Quim

**Comment by janniten** [comment]
Hi Quim,
Yes no problem. I can share the code.
I was also working from the elastic side improving index mapping definition
using index templates and more precise data type definitions.
I can also share that work.
Please email me outside of this thread and I'll sent you what I have
I'm glad to help :)
Regards
Ana

**Comment by reactor7171** [comment]
Hi @janniten,
Will do, I am missing though your personal email :) I sent you a LinkedIn request though in case you want to keep there the conversation.

**Comment by reactor7171** [comment]
I am going to close both #42 and #117 in pro of #64 , as all of them are related to the ingestion of XML output files, and ingesting the Nessus XML file will fix both of those issues.
