### ISSUE TITLE
Too much setup information in the docker container

### ISSUE THREAD

**Issue by infosec-alchemist** [HASecuritySolutions/VulnWhisperer#125]
I don't believe the docker container should not include the docker-compose, elasticsearch, etc information.  I would recommend that the docker image be focused specifically on running a single vulnwhisper instance.

**Comment by reactor7171** [comment]
Hi @infosec-alchemist,

If you just want the docker-compose for vulnwhisperer, you can just comment our from the docker-compose.yml file the ELK instances or directly just download the Dockerfile of VulnWhisperer instead of the docker-compose, as the docker-compose is basically the existent VulnWhisperer Dockerfile with the rest of the ELK stack.

Still, if you just want to run VulnWhisperer, I believe the best is to just create a python virtualenv and run there directly the code from the repository, instead of running the docker-compose.

I believe you are not using the docker-compose for the objective that it has been created and that there are many other ways to do what you want to achieve; if I am missing something could you please highlight it?

Cheers!

**Comment by infosec-alchemist** [comment]
Sorry, I misspoke.

The Docker image stored in docker Hub (https://hub.docker.com/r/hasecuritysolutions/vulnwhisperer/) includes, in the image, all the docker files for setting up elk.  And docker-compose, etc.  Since this is the VulnWhisperer docker image, and thus would just be running VulnWhisperer, I don't believe it should also include the code for running ELK inside that image.

**Comment by reactor7171** [comment]
Hi @infosec-alchemist,
I now understand what you mean :D yes you are right, this is because it is pulling directly the code from the VulnWhisperer repo, which has those. We have been internally talking about separating the docker-compose from the main repo, in order to have things clear, but it is something that is still in our backlog.

Regarding the resource files of Logstash and Kibana, we would still leave them in the VulnWhisperer repo, although I am working on unifying on a standard the modules, so we would have one single file, and my intention is to put out on a resources folder those files in order to keep that organised.

Thanks for the heads up, and don't hesitate to raise up any other doubts ^^

Cheers!

**Comment by cybergoof** [comment]
I think this can be closed based on pull request #132
