### ISSUE TITLE
Inconsistency in directory naming in Docker

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#128]
The docker file is attempting to interact with a  /opt/VulnWhisperer, but the directory name in the container is /opt/vulnwhisperer.

I'm seeing multiple docker repositories in the docker-hub registry.  So I'm not sure which one is legit or should be the main used.

**Comment by reactor7171** [comment]
Hi @cybergoof,
Are you checking directly the Dockerfile or the docker-compose file? Did you follow the instructions at https://github.com/HASecuritySolutions/VulnWhisperer/wiki/docker-compose-Instructions?

There is a folder with the config files for docker at https://github.com/HASecuritySolutions/VulnWhisperer/tree/master/docker, as it is not only the path that changes in the docker-compose, but it is true that the Dockerfile hasn't been updated; this is something we will need to take care.

If you find any other issues please don't hesitate to raise them in order to have them fixed.

Cheers!

**Comment by cybergoof** [comment]
I was confused.  I was looking at an old docker image that I still had running rather than the new one.

I'm getting confused because the dockerfile is not in the source repo, but in another repo.

**Comment by reactor7171** [comment]
Hi @cybergoof,

You are right, I still don't have admin rights over that repository, so I wasn't able to accept my own PR with the changes needed to update the dockerfile repo from the source repo/organization.
@austin-taylor would you mind giving me write rights at the https://github.com/HASecuritySolutions/docker_vulnwhisperer repository in order to fix that? We would also need the DockerHub account in order to update the file on that repository, in order to be able to pull easily the image from docker directly.

Cheers!
