### ISSUE TITLE
allow all ini arguments to be passed in

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#13]
allowing arguments instead of an ini file will help reduce file dependence when running in Docker containers.

All ini files can be sent in the docker run, or in a docker-compose file.

**Comment by reactor7171** [comment]
Ini files are working with the docker-compose file, currently allowing VulnWhisperer to run without any other argument than the specification of the config file. In the config file, the different modules have an "enable" variable in order to run it.

This will work automatically with the official [VulnWhisperer docker](https://github.com/HASecuritySolutions/docker_vulnwhisperer), which is uploaded in Docker Hub.

**Comment by cybergoof** [comment]
Sorry, I was just seeing this.

The intention of the request was to provide a way to launch the docker containers without having a file on disk, which can contain private information.

**Comment by reactor7171** [comment]
Hi @cybergoof,

This is something tricky, as at the end we are working with VulnWhisperer towards a more modular project, both for integrating new scanners/frameworks as integrating other tools; last one was jira, but I also would like to integrate Slack; also among the different scanners, there are different dependencies, e.g. the qualysapi dependency requires an ini file with the creds in order to work, so we would need to think how to do a workaround to avoid that. 

I think at the end VulnWhisperer could end up turning into more of a service instead of a run once program, but this is something that will be seen as time goes on ^^

Cheers!
