### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by austin-taylor** [HASecuritySolutions/VulnWhisperer#15]
Logging should be implemented for nightly runs to shows status of jobs

**Comment by reactor7171** [comment]
I am going to close both #15 and #11 in pro of ticket #78.

The objective of the ticket is:

- Improve overall logging on the vulnwhisperer project.
- Include status of jobs logs.
- Includen error logs in order to track failures on the project.

This will also be easier to track once python tests are implemented in order to make sure that every code addition is not breaking other code parts from the project.
