### ISSUE TITLE
Vulnwhisperer error with openvas

### ISSUE THREAD

**Issue by HKcyberstark** [HASecuritySolutions/VulnWhisperer#155]
**Describe the bug**
I am running a fresh installation of vulnwhisperor in centos
- installed dependencies
- cloned github and configured the framework ini file
- created directory for write_path and databas path.  [ /opt/vulnwhisperer/data/openvas]
- gave higher permission chmod 777 to path directories
- ran vulnwhisperer with below command from root folder as root user
**vuln_whisperer -c </path/to/configs/>frameworks_example.ini -s openvas**

**getting below error**
import qualysapi
Import error : no module named qualysapi

**Affected module**
vulnwhisperor run command for openvas

**Screenshots**
![image](https://user-images.githubusercontent.com/40884455/54571280-f4e99800-4a1c-11e9-96e5-066f74b48a2d.png)

**System in which VulnWhisperer runs (please complete the following information):**
- centos 7

Thanks in advance and appreciate your support !!

**Comment by reactor7171** [comment]
This has been solved on Slack, the issue is that the current master branch requires one to do `git submodule init && git submodule update && cd deps/qualysapi && python setup.py install`. This is solved in the beta-1.8 branch, as we merged VulnWhisperer's fork of qualysapi with the official library.

Closing the ticket.
