### ISSUE TITLE
Help: To Use VulnWhisper

### ISSUE THREAD

**Issue by HiteshPatel0101** [HASecuritySolutions/VulnWhisperer#20]
HI All,

I need help,I have configured VulnWhisper on my winodws 7 64x.
Configured it and run as per Git Readme.
Now I have Nessus data in CSV.
Can you guide me now what to do with CSV, so i can get complete scene in one page.
Graph and top 10 data as shown in screenshot.

Thanks in advance.

**Comment by reactor7171** [comment]
Hi @HiteshPatel0101,

In order to do that, you should set up an ELK environment as it is mentioned on the README, with the logstash and kibana files listed in the project on the expected paths.

There is also now a docker-compose, in case you don't want to set up the whole stack, allowing you to, after following the instructions, set up the whole environment without further dependencies.

I will close this issue now as it is obsolete and hasn't had any follow up, if you have any other question please raise another issue :)
