### ISSUE TITLE
[Request] Pull Nessus "Diff" CSV 

### ISSUE THREAD

**Issue by LukeDInfosec** [HASecuritySolutions/VulnWhisperer#210]
I was just wondering if there is a way to only pull nessus Diff data so that only NEW Vulnerabilities pop up, not ones previously detected from the previous CSV Files .... is this possible?

**Comment by reactor7171** [comment]
Hi @LukeDInfosec,

I understand what you mean, although this is not the original idea behind the project: the intention is to have a centralized place with all of the results of the different scanners, so that you can manage the results as one; if you were to manage the data as you mentioned, you would get to a new set of use case, as a way to differentiate the "new" results from the diff those vulnerabilities that are new from those that no longer exist, and how to manage those results properly to "cancel" with the old ones in logging systems as ELK or Splunk. 

I have the feeling that what you want is not to track vulnerabilities, but get the notifications of those new vulnerabilities in some other system; could you explain on more detail what is exactly the use case you have that you would want to cover and see if there is some other way to cover it?

Cheers!
