### ISSUE TITLE
A more thorough README is underway with setup instructions

### ISSUE THREAD

**Issue by lejonpart** [HASecuritySolutions/VulnWhisperer#25]
"Next you'll need to import the visualizations into Kibana and setup your logstash config"

Well you are so right this is needed because I'm stuck here.

/Regards

**Comment by austin-taylor** [comment]
You'll want to follow import the json files in the kibana folder using the import instructions here

https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html

**Comment by lejonpart** [comment]
Thanks that got me one step closer but still no cigar :(
I have not any data yet in elastic since I cant get passed the "Import ElasticSearch Templates"

When I import the Kibana .. json I get the following.
"Saved Objects: Could not locate that index-pattern (id: logstash-vulnwhisperer-*),"

So where do I import the elastic ...json?

Regards

**Comment by austin-taylor** [comment]
Don't worry about the elastic json for now.  That's a template. If your logstash config is in pave,  go ahead and process your reports

**Comment by reactor7171** [comment]
This issue has not been encountered since the README.md was updated and clarified. 

The reason of not locating the index pattern it was most probably related to a logstash issue, where the scanner files are not being parsed and submitted to ElasticSearch as expected, creating all the data under the "logstash-vulnwhisperer-*" pattern.

A related issue was reported in #83, and [this](https://github.com/austin-taylor/VulnWhisperer/issues/83#issuecomment-406283999) was the solution to it.

Closing ticket as resolved due to it being fixed, obsolete and not revisited by OP.
