### ISSUE TITLE
Is it possible to upload nessus,qualys XML reports directly to Vulnwhisperer?

### ISSUE THREAD

**Issue by yellowflash2791** [HASecuritySolutions/VulnWhisperer#27]

**Comment by austin-taylor** [comment]
I'm not sure what you mean. You already have the files?

**Comment by Wyv3rnSec** [comment]
I believe they already have the file via a Nessus export (A .nessus or .csv file) and are looking to have Logstash import them.

While more detail is needed from @yellowflash2791 I am not sure these would work for import. 

Firstly, the Logstash input filters are looking for CSV format not XML. 

Also, for clarification VulnWhisperer is utilized to pull the data from your Vulnerability Framework of choice. If you already have the XML/CSV files you could do some tricky logstash filtering to get them imported into ELK but the filters & Json visualizations here wont apply.

**Comment by reactor7171** [comment]
Hi @yellowflash2791 ,

@Wyv3rnSec is correct about it, plus VulnWhisperer is not only pulling the data from your Vulnerability Frameworks, but it is as well mapping it in a different way in order to standardize it in the process, being not the original but the modified results stored locally. 

This is not something that we are looking forward at the moment, as the intention of VulnWhisperer is to automate the Vulnerability Management part, and we are doing this by allowing it to access the scanner data and standardize so that one solution works as expected with whatever scanner you have.

I will close this ticket.
