### ISSUE TITLE
[ELK6] Kibana Visualisations

### ISSUE THREAD

**Issue by Gee94** [HASecuritySolutions/VulnWhisperer#34]
Importing the vulnWhispererBaseVisuals.json adds VulnWhisperer - Risk: Critical (Also info, low, medium, high and total) as a 'goal' type visualization which without alteration prevents the visualization from working. 
Changing the type to 'gauge' manually in the JSON file seems to resolve this.

**Comment by austin-taylor** [comment]
Which version of Kibana are you using

**Comment by Gee94** [comment]
Tried with 6.1.3 and 6.2.2 doesn't like either.

**Comment by austin-taylor** [comment]
Okay - haven't made visuals for 6.x yet.  I'll work on that soon.  Currently supports 5.6. Elastic upgrades a very frequently so it's hard to keep up with.  Check our release section for compatible releases

**Comment by jonnystarky** [comment]
find * | grep vulnWhispererBaseVisuals.json
opt/VulnWhisperer/kibana/vuln_whisp_kibana/1000_vulnWhispererBaseVisuals.json
and import 
http://YOUIPorLOCALHOST:5601/app/kibana#/management/kibana/objects?_g=(refreshInterval:(display:on,pause:!f,value:0),time:(from:'2003-05-05T13:32:59.834Z',mode:absolute,to:'2004-05-04T13:32:59.835Z'))&_a=(tab:dashboards)
klick the import button
<img width="1146" alt="bildschirmfoto 2018-05-01 um 17 08 49" src="https://user-images.githubusercontent.com/23657572/39478342-74a6754e-4d62-11e8-93fb-1cea59f4cfef.png">

**Comment by austin-taylor** [comment]
Yes @spartantri - I just need to rebuild dashboard and update mappings.

**Comment by Dom1001** [comment]
Dashboard can be run under 6.x. I`ve copied the configs: kibanaSavedObjectMeta.searchSourceJSON , uiStateJSON ,visState into new visuals. Seems to work because the dashboard didn`t crash.
![grafik](https://user-images.githubusercontent.com/25900975/40798229-cd2be4b4-650a-11e8-953e-6b529bb7fe19.png)

The new problem is that the float values are not interpreted
![grafik](https://user-images.githubusercontent.com/25900975/40798313-017a796a-650b-11e8-8b58-2c1ba4fdfc48.png)
![grafik](https://user-images.githubusercontent.com/25900975/40798331-135e9936-650b-11e8-9d14-5bfeb26f8710.png)
 
Someone has an idea?

**Comment by Dom1001** [comment]
The broken visuals are Risk: low, Risk: medium, Risk: High, Risk: Critical and Risk: Total

**Comment by austin-taylor** [comment]
I need to upgrade them to 6.2.2. If someone makes new visuals in 6.2.2 and submits a PR I'll approve it and create a new version of VulnWhisperer

**Comment by Dom1001** [comment]
This Visuals should work. No problems anymore. Float failures were based on failures in the logstash config.
https://github.com/Dom1001/VulnWhisperer/blob/master/kibana/vuln_whisp_kibana/VulnWhisperer-Risk%20Visuals_es6.json

**Comment by pemontto** [comment]
@Dom1001 they don't throw horrible errors, but they also have no styling and no colour. I've tried replicating the background colours with the Gauge, Goal and Metric visualisation types to no avail.

The problem is the goal/gauge type no longer supports the styling we had in Kibana 5. The closest you can get to the original gauges is a "Visual Builder" Metric, but that's sub-optimal because the maximum interval is 1y 👎

![vulnwhispv6](https://user-images.githubusercontent.com/939704/41342524-c969dedc-6f3f-11e8-8226-61870d4e22dc.png)

**Comment by reactor7171** [comment]
Will close both #76 and #34 in pro of #86 in order to unify issues that are related to the same.
