### ISSUE TITLE
Improved Readme for importing nessus csv into Logstash

### ISSUE THREAD

**Issue by GeeksikhSecurity** [HASecuritySolutions/VulnWhisperer#36]
I have a fresh install of Elasticsearch, Logstash, Kibana, Nessus in default locations on the same Ubuntu 16.04 server VM and managed to import the Nessus scans and got the csv file in '/opt/vulnwhisp/nessus/My Scans' folder. Need some guidance on importing the CSV files into Logstah or Elasticsearch for a new index. Sorry am new to Elastic stack and trying to get VulnWhisperer operational and will be happy to contribute instructions on how to setup the entire setup.

Thanks in advance for your help.
Singh

**Comment by Wyv3rnSec** [comment]
Hey @GeeksikhSecurity I referenced this in another issue (#21). While the tool is more focused pulling the data from the various Vulnerability frameworks, a lot of ELK setup falls on the individual since each environment can vary so wildly. 

With this said ill try and edit the readme with **SAMPLE** install for a ELK node and see if @austin-taylor will accept.

As an edit there is a docker I believe he has setup.

**Comment by austin-taylor** [comment]
Thank you for your contribution @Ryandress - I've merged your readme and always appreciate extra documentation!
