### ISSUE TITLE
Add the 'plugin family' to data collected for searching/grouping

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#42]
Adding the 'plugin family' to the logstash will help with grouping vulns.

happy to work on this if you like.

**Comment by austin-taylor** [comment]
Would make a nice addition :)

**Comment by reactor7171** [comment]
This is something that will need to be added when parsing and formatting the data pulled from the scanner, as in the local file with the vulnerabilities the field is already missing. Shouldn't be complicated though to include it in both the local file and logstash configuration file.

**Comment by reactor7171** [comment]
I retract from what I said in the last comment, apparently we are using the raw Nessus CSV export file, which does NOT include the 'Plugin Family' field. Would need to check that the 'nessus' file does actually have it, and if so, modify the module so that it parses that file.

Edit: As I though, the ".nessus" file contains everything related to the scan, including the "plugin family". This comes though with downsides, we would need to change the nessus plugin so that it gets the ".nessus" XML files and parses and restructures all the information there; it also weights double the CSV's file size due to the amount of extra info.
Having this is something that would be good to have, as also we are having much less info from Nessus scans than Qualys scans (14 to 24 fields respectively), but I don't think this is a priority right now.

**Comment by cybergoof** [comment]
Would it be a significant data increase to have logstash add the plugin family at ingest time?

**Comment by reactor7171** [comment]
Hi @cybergoof,

Its not really a matter of data increase, but as far as I have seen (using Nessus v6), the data that is being downloaded from Nessus with VulnWhisperer is the CSV file, which doesn't have the Plugin Family field. We would need to change the Nessus source to be either the XML or the ".nessus" file, and parse and adapt it to VulnWhisperer.

I would also be interested in having the Plugin Family field, but the amount of effort and refactoring that requires having that change compared with the benefits its too big, and currently we have other priorities to work in unfortunately.

Definitely something on our TODO list.

**Comment by cybergoof** [comment]
mmmmm.....yeah.  Its a nice to have, but probably not priority.

**Comment by reactor7171** [comment]
I am going to close both #42 and #117 in pro of #64 , as all of them are related to the ingestion of XML output files, and ingesting the Nessus XML file will fix both of those issues.
