### ISSUE TITLE
Qualys VM setup

### ISSUE THREAD

**Issue by mrnewman** [HASecuritySolutions/VulnWhisperer#51]
Hello,
I'm hoping this is a simple question.  But for the moment I am unable to resolve.
I have lots of data in Qualys VM and would like to try VulnWhisperer.  However, it appears the default Qualys pull request is for the WAS application.  How/where do I set up VulnWhisperer for Qualys VM?
Thanks!
Richard

**Comment by vonswoopington** [comment]
I am having the same issue.  Anyone know how to pull from Qualys VM?

**Comment by pemontto** [comment]
This is not yet implemented, it uses a different API to WAS.

**Comment by reactor7171** [comment]
Hey @vonswoopington, this feature has been released, you can give it a try :)

**Comment by reactor7171** [comment]
Hey @mrnewman,

The template_id is actually not used in the Qualys VM integration, this has been an slipping error as per copying the qualys template into the qualys_vuln; you can just ignore that value.

Cheers,
Quim

**Comment by mrnewman** [comment]
Thanks.
There appears to be an authentication issue with the Qualys VM piece.  I have actually locked my account due to too many 'bad' attempts.  However, when I use the same configuration for Qualys WAS the credentials work.  I've tried digging through the code, but I can't locate the code for logging in.

Ideas?

Thanks,
Richard

**Comment by kraigu** [comment]
The authentication code will be in the qualysapi dependency, https://github.com/austin-taylor/VulnWhisperer/tree/master/deps/qualysapi which is a customised version of the original libraries https://github.com/paragbaxi/qualysapi

@mrnewman I haven't played with this yet, been distracted by other things, but if I get it going I'll let you know.

@qmontal As an interested party (the code Parag based his library on was originally developed by a colleague) I've been meaning to ask why the fork/customisation vs pushing changes upstream.

**Comment by vonswoopington** [comment]
@qmontal thank you for the update! this is great news!

**Comment by reactor7171** [comment]
@mrnewman sorry to hear that, as @kraigu says, the authentication is done with qualysapi. Are you sure that the account you are using does have API permissions? I was already using a custom piece of code for retrieving Qualys VM results from the API and it worked like charm from the first moment; we are currently using it in prod.

@kraigu I am new to the development of VulnWhisperer and the fork was already done by the time I got here, although I guess it has been done for assure that VulnWhisperer was using a version of qualysapi that had been thoroughly tested and has no issues. 

As a user of qualysapi myself though, also having colleagues who have contributed to the code, qualysapi has been pretty much discontinued for the last years, and this has meant issues on our inhouse projects due to Qualys changing stuff on their side, breaking our code as a consequence. I don't think there will be much difference between the original and the fork we are using.

**Comment by kraigu** [comment]
@qmontal Yeah, that's fair enough. I'd just rather see fixes made available to general users of that library, with some cooperation between the library maintainer and the maintainers of this project to ensure that things don't break. I do agree that generally, development Over There has more or less stalled. I'm interested to know what pieces of your code have broken though, since I've not had to update very little over here. That discussion is probably best outside of this thread though. :)

**Comment by mrnewman** [comment]
Hi @qmontal.  Yeah, validating the creds has been a bit tricky.  I have a $ in my password which sometimes causes trouble with scripts.  When I invoke the Qualys API natively using curl I have to escape the $ character with a backslash \.  

I have tested the qualysapi within python manually using the a = qualysapi.connect() method, supplying my credentials, then calling a print a.result('about.php').  This works.

And oddly enough, the vuln_whisperer script now works.  The only difference is the ID I am using.  The first ID was my manager ID.  I switched to a test ID, which is only a reader.  For the moment the script is actively pulling scans.

Qualys is notorious for changing how stuff works.  I'm working multiple paths on how to use raw Qualys data most effectively.  The host vm detection API has some tremendous abilities, albeit with some limitations, such as, no vulnerability information, just the results, and if you use the CSV, host tags are not included.  We have a number of tags which add insight to our data, such as global region, PCI, etc.  When building dashboards, using tags help to shape the data effectively.

Since my issue has been resolve, this thread can be closed.  If anyone would like to discuss further, please feel free to reach out to me at m.richard.newman@gmail.com.

Thanks!
Richard

**Comment by reactor7171** [comment]
@kraigu sure, I can talk with my colleague who was checking and fixing the issues and see if he can push to the repo; we don't really have much time for this kind of stuff so we do emergency fixes and continue working with other stuff... you can reach me at qmontal@protonmail.com

@mrnewman glad that it worked! if there is anything that you see could be improved or changed, just ping out as it will help also us ^^

@austin-taylor mentioned on creating a VulnWhisperer Slack instance where we could communicate easier regarding the project, so it would be good to have the interested ones there :D 
@austin-taylor can we close the ticket?

BR,
Quim
