### ISSUE TITLE
trim results of argument values in case of extra space

### ISSUE THREAD

**Issue by cybergoof** [HASecuritySolutions/VulnWhisperer#6]

**Comment by reactor7171** [comment]
Hi @cybergoof,

I have been testing the "argsparse" module that we are using in VulnWhisperer in order to retrieve the arguments from the command ran, and it is actually itself taking care of stripping the extra spaces from the arguments, so there is no need of any other implementation.

As the improvement is already existent in the project, I will close this ticket.

Cheers!
