### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by austin-taylor** [HASecuritySolutions/VulnWhisperer#78]

**Comment by reactor7171** [comment]
Related to https://github.com/austin-taylor/VulnWhisperer/issues/15 and #11.

**Comment by reactor7171** [comment]
I am going to close both #15 and #11 in pro of this ticket (#78).

The objective of this ticket is improve overall logging on the vulnwhisperer project, including status of jobs and error logs in order to track failures on the project.

This will also be easier to track once python tests are implemented in order to make sure that every code addition is not breaking other code parts from the project.
