### ISSUE TITLE
Can't get reports from OpenVAS

### ISSUE THREAD

**Issue by MauJFernandezUVR** [HASecuritySolutions/VulnWhisperer#98]
I'm having this error when getting the reports from OpenVAS 9 (vulnwhisperer commit 078bd9559e4d2a9bc2343b44d79b9166a925cfe2):

```[root@infrapps vulnwhisp]# python -d /opt/vulnwhisperer/bin/vuln_whisperer -c /opt/vulnwhisperer/configs/frameworks_example.ini -s openvas
[INFO] Connected to database at /opt/vulnwhisperer/data/database/report_tracker.db
[FAIL] ERROR: 'NoneType' object has no attribute 'text'
```

I have an older vulnwhisperer installation in another server with commit 46be3c71ef36e5dc413cc00626b279a39810c49e and it gets the reports OK.

**Comment by reactor7171** [comment]
Hi @MauJFernandezUVR ,

Thank you for flagging up this OpenVAS issue, did you see where exactly it failed in the code? I believe there has been no changes on the OpenVAS code part, so I am a bit surprised that it broke.

We are planning on implementing tests on the project in order to make sure that everything is working as expected after every change, in order to not have this kind of issues where something breaks with a code update :)

**Comment by ManuelFFF** [comment]
Hi,

I am having the same issue, but I don't see a valid response about how to fix it. Please help

```
INFO:root:main:Running vulnwhisperer for section openvas
INFO:vulnWhispererBase:__init__:Connected to database at /opt/VulnWhisperer/data/database/report_tracker.db
INFO:vulnWhispererOpenVAS:directory_check:Directory already exist for /opt/VulnWhisperer/data/openvas/ - Skipping creation
ERROR:vulnWhispererOpenVAS:__init__:Unable to establish connection with OpenVAS scanner. Reason: 'NoneType' object has no attribute 'text'
ERROR:root:main:__init__() should return None, not 'bool'
ERROR: __init__() should return None, not 'bool'
```

**Comment by ManuelFFF** [comment]
Hi,

Any help available?

Thank you
